version: '3.1'

services:
  app:
    image:  '2bb5300f9c76'
    container_name: app
    environment:
      - DB_URL = jdbc:postgresql://postgres:5432/test
      - DB_USER = postgres
      - DB_PASSWORD = admin
    ports:
    - 8081:8081
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

