version: '3.1'

services:
  app:
    image: '5e20fe5a49b1'
    container_name: app
    environment:
      - DB_URL=jdbc:postgresql://postgres:1234/Grani
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
    ports:
      - 80:80
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

